services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@default.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "89:80"
    networks:
      - postgres-network
  postgres-pooweb2:
    image: postgres
    container_name: postgres_pooweb2_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - /home/rodrigo/data/postgres:/var/lib/postgresql/data
networks:
  postgres-network:
    driver: bridge